services:
  mcserver:
    container_name: mcserver
    image: itzg/minecraft-server
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: true
      MEMORY: "2G"
      DIFFICULTY: "hard"
      TYPE: "PAPER"
      VERSION: "1.21.3"
      SNOOPER_ENABLED: false
      ONLINE_MODE: false
      SERVER_NAME: "azuremc"
      RESOURCE_PACK: https://cdn.modrinth.com/data/ItHr72Fy/versions/pbKmDVlm/Fullbright-UB-1.21.zip
      RESOURCE_PACK_ENFORCE: true
      # SPIGET_RESOURCES: "82528"
    env_file: .env
    volumes:
      - ./data:/data
    depends_on:
      mcrestore:
          condition: service_completed_successfully
    restart: unless-stopped

  mcbackup:
    container_name: mcbackup
    image: itzg/mc-backup
    environment:
      RCON_HOST: mcserver
      BACKUP_INTERVAL: "10m"
      INITIAL_DELAY: 0
      BACKUP_METHOD: "rclone"
    env_file: .env
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
      - ./rclone.config:/config/rclone/rclone.conf
    depends_on:
      mcserver:
        condition: service_healthy
    restart: unless-stopped

  mcrestore:
    container_name: mcrestore
    image: itzg/mc-backup
    entrypoint: restore-tar-backup
    volumes:
      - ./data:/data
      - ./backups:/backups:ro
    restart: "no"
