services:
  swag:
    container_name: swag
    image: lscr.io/linuxserver/swag:latest
    cap_add:
      - NET_ADMIN
    env_file:
      .env
    environment:
      PUID: 1000
      PGID: 1000
      VALIDATION: dns
      DNSPLUGIN: cloudflare
      ONLY_SUBDOMAINS: true
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
    restart: unless-stopped

  mcserver:
    container_name: mcserver
    image: itzg/minecraft-server
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: true
      MEMORY: "2G"
      DIFFICULTY: "hard"
      TYPE: "PAPER"
      VERSION: "1.21.3"
      SNOOPER_ENABLED: false
      ONLINE_MODE: false
      ENABLE_COMMAND_BLOCK: true
      SERVER_NAME: "azuremc"
      RESOURCE_PACK: https://cdn.modrinth.com/data/ItHr72Fy/versions/pbKmDVlm/Fullbright-UB-1.21.zip
      RESOURCE_PACK_ENFORCE: true
      RCON_CMDS_STARTUP: |-
        gamerule keepInventory true
        gamerule playerSleepingPercentage 0
        execute in the_nether run gamerule keepInventory true
        execute in the_end run gamerule keepInventory true
      # SPIGET_RESOURCES: "82528"
    env_file: .env
    volumes:
      - ./data:/data
    depends_on:
      mcrestore:
          condition: service_completed_successfully
    restart: unless-stopped

  mcbackup:
    container_name: mcbackup
    image: itzg/mc-backup
    environment:
      RCON_HOST: mcserver
      BACKUP_INTERVAL: "1h"
      INITIAL_DELAY: "5m"
      BACKUP_METHOD: "rclone"
    env_file: .env
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
      - ./rclone.config:/config/rclone/rclone.conf
    depends_on:
      mcserver:
        condition: service_healthy
    restart: unless-stopped

  mcrestore:
    container_name: mcrestore
    image: itzg/mc-backup
    entrypoint: restore-tar-backup
    volumes:
      - ./data:/data
      - ./backups:/backups:ro
    restart: "no"

# execute @e[type=PigZombie,c=1] ~ ~ ~ setblock -203 14 129 repeating_command_block[conditional=true]{Command:"/gamerule keepInventory true",auto:1b}
# execute in minecraft:the_nether run setblock -118 94 106 repeating_command_block[conditional=true]{Command:"/gamerule keepInventory true",auto:1b} replace
