---
- name: Cloud playbook
  hosts: cloudgroup
  become: true

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Clone mcserver repository  # noqa: latest
      ansible.builtin.git:
        clone: true
        repo: "https://www.github.com/dhzdhd/mcserver"
        dest: "/home/server"

    - name: Copy local backups to server
      ansible.builtin.copy:
        src: "../../../backups/"
        dest: "/home/server/backups/"
        mode: "preserve"

    - name: Copy local .env file to server
      ansible.builtin.copy:
        src: "../../../.env"
        dest: "/home/server/"
        mode: "preserve"

    - name: Copy local rclone config to server
      ansible.builtin.copy:
        src: "../../../rclone.config"
        dest: "/home/server/"
        mode: "preserve"

    - name: Run server with docker compose
      community.docker.docker_compose_v2:
        project_src: "/home/server"

    - name: Copy nginx config to swag
      ansible.builtin.copy:
        src: "../../../nginx.conf"
        dest: "/home/server/swag/nginx/proxy-confs/mc.subdomain.conf"
        mode: "preserve"

    - name: Copy cloudflare config to swag
      ansible.builtin.copy:
        src: "../../../cloudflare.ini"
        dest: "/home/server/swag/dns-conf"
        mode: "preserve"

    - name: Restart swag container
      community.docker.docker_container:
        name: swag
        restart: true
